sonar.projectKey=SwatiSharma29194_easeMind
sonar.organization=swatisharma29194
sonar.projectName=EaseMind
sonar.sources=EaseMind
sonar.tests=EaseMindTests
sonar.host.url=https://sonarcloud.io
sonar.coverageReportPaths=sonar-reports/coverage.xml
