name: SonarCloud Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sonar:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Xcode Tests
        run: xcodebuild test -project EaseMind.xcodeproj -scheme EaseMind -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16' -enableCodeCoverage YES -resultBundlePath build/result.xcresult

      - name: Install SonarScanner
        run: brew install sonar-scanner

      - name: Convert Coverage Report
        run: |
          mkdir -p sonar-reports
          bash xccov-to-sonarqube-generic.sh build/result.xcresult > sonar-reports/coverage.xml

      - name: Run SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner -Dsonar.projectKey=SwatiSharma29194_easeMind -Dsonar.organization=swatisharma29194 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
